# directory creation is handled by Hydra
hydra:
  sweep:
    dir: ./outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}/seed=${seed}
  run:
    dir: ./outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed

# experiment parameters
debug: false
save_dir: 'experiments_logs'
use_wandb: true
experiment_name: 'DANN_HAR'
run_description: 'run_DANN_HAR'
da_method: 'DANN'
iwv_method: 'IWV_Domain_Classifier'
data_path: 'data'
dataset: HAR
backbone: CNN
num_runs: 1
device: 'cuda:0'
seed: 1

# sweep parameters
is_sweep: False
num_sweeps: 30
sweep_project_wandb: 'TEST_SOMETHING'
wandb_entity: ''
hp_search_strategy: 'random'
metric_to_minimize: 'src_risk'

run_params:
  log_dir: './'
  save_dir: './'
  with_timestamp: False
